version: '3.7'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow-net

  webserver:
    image: apache/airflow:2.2.2
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - airflow-net
    depends_on:
      - postgres
    command: webserver

  scheduler:
    image: apache/airflow:2.2.2
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - airflow-net
    depends_on:
      - postgres
    command: scheduler

  airflow-init:
    image: apache/airflow:2.2.2
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    networks:
      - airflow-net
    depends_on:
      - postgres
    entrypoint: >
      bash -c "
      airflow db upgrade;
      airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com;
      "

volumes:
  postgres-db-volume:

networks:
  airflow-net:
