version: '3.7'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow-net

  webserver:
    image: apache/airflow:2.2.2
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ''
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - airflow-net
    depends_on:
      - postgres
    command: webserver

  scheduler:
    image: apache/airflow:2.2.2
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - airflow-net
    depends_on:
      - postgres
    command: scheduler

volumes:
  postgres-db-volume:

networks:
  airflow-net:
